#!/usr/bin/env bash
#
# Print the socials - indended to be passed to `tools/box`
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: April 05, 2025
# License: MIT

. ./theme || exit
. ./tools/readarray || exit 1

# readarray SOCIALS << "EOF"
# Instagram|https://ysap.sh/instagram
# YouTube|https://ysap.sh/youtube
# Patreon|https://ysap.sh/patreon
# Discord|https://ysap.sh/discord
# Twitch|https://ysap.sh/twitch
# EOF

readarray SOCIALS << "EOF"
Email|janyajoshi18@gmail.com
LinkedIn|https://www.linkedin.com/in/janyajoshi/
Youtube|https://www.youtube.com/@janyajoshi
NPM|https://www.npmjs.com/~janyajoshi
EOF

UNDERLINE=$'\x1b[3m'

for line in "${SOCIALS[@]}"; do
	IFS='|' read -r name url <<< "$line"

	echo -n "$COLOR2$name$RST"
	echo -n '|'
	echo -n "$UNDERLINE$COLOR2$url$RST"
	echo
done
